@server = http://localhost:3000

#게시글 조회
GET {{server}}/book

###게시글생성
POST {{server}}/book
Content-Type: application/json

{
  "title": "The Hobbit",
  "author": "J.R.R. Tolkien",
  "year": 1937,
  "isAvailable": true
}
###특정게시글조회
GET {{server}}/book/1


###특정게시글 삭제
DELETE {{server}}/book/1


###게시글 수정
PUT {{server}}/book/1
Content-Type: application/json

{
  "title": "1984",
  "author": "George Orwell",
  "year": 1949,
  "isAvailable": false
}
